# -*- coding: utf-8 -*-

"""
AI Simscape Model Generator - Generating MATLAB Simscape Models using Large Language Models.
Copyright (C) 2024  Patrick Hummel

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

--------------------------------------------------------------------------------------------

Abstract connections used in the abstract system model generated by the AI.

Last modification: 28.11.2023
"""

__version__ = "1"
__author__ = "Patrick Hummel"

from src.abstract_model.abstract_components import AbstractComponent


class AbstractConnection:

    def __init__(self, from_component: AbstractComponent, from_port: str, to_component: AbstractComponent, to_port: str):
        self._from_component = from_component
        self._from_port = from_port
        self._to_component = to_component
        self._to_port = to_port

    def __str__(self):
        return f"{self._from_component.unique_name} -> {self._to_component.unique_name}"

    @property
    def from_component(self) -> AbstractComponent:
        return self._from_component

    @property
    def from_port(self) -> str:
        return self._from_port

    @property
    def to_component(self) -> AbstractComponent:
        return self._to_component

    @property
    def to_port(self) -> str:
        return self._to_port
