# -*- coding: utf-8 -*-

"""
Abstract connections used in the abstract system model generated by the AI.

Last modification: 28.11.2023
"""

__version__ = "1"
__author__ = "Patrick Hummel"

from src.abstract_model.abstract_components import AbstractComponent


class AbstractConnection:

    def __init__(self, from_component: AbstractComponent, from_port: str, to_component: AbstractComponent, to_port: str):
        self._from_component = from_component
        self._from_port = from_port
        self._to_component = to_component
        self._to_port = to_port

    def __str__(self):
        return f"{self._from_component.unique_name} -> {self._to_component.unique_name}"

    @property
    def from_component(self) -> AbstractComponent:
        return self._from_component

    @property
    def from_port(self) -> str:
        return self._from_port

    @property
    def to_component(self) -> AbstractComponent:
        return self._to_component

    @property
    def to_port(self) -> str:
        return self._to_port
